server:
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: amigoscode
    password: password
  sql:
    init:
      continue-on-error: true
      mode: always
      platform: postgres
      schema-locations:
        classpath:db/schema.sql
      data-locations:
        classpath:db/data.sql